dialog:
	pyuic4 buildgraphicDialog.ui -o buildgraphicDialog.py
	pyuic4 setWidthDialog.ui -o setWidthDialogUi.py
	pyuic4 selectAxisIdDialog.ui -o selectAxisIdDialogUi.py
	pyuic4 aboutDialog.ui -o aboutDialogUi.py
