# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'buildgraphicDialog.ui'
#
# Created: Wed Sep  9 10:44:37 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog_Build(object):
    def setupUi(self, Dialog_Build):
        Dialog_Build.setObjectName("Dialog_Build")
        Dialog_Build.resize(684, 354)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_Build.sizePolicy().hasHeightForWidth())
        Dialog_Build.setSizePolicy(sizePolicy)
        Dialog_Build.setMinimumSize(QtCore.QSize(684, 354))
        Dialog_Build.setMaximumSize(QtCore.QSize(684, 354))
        self.gridLayoutWidget = QtGui.QWidget(Dialog_Build)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 671, 341))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pathLogfile = QtGui.QLineEdit(self.gridLayoutWidget)
        self.pathLogfile.setObjectName("pathLogfile")
        self.gridLayout.addWidget(self.pathLogfile, 0, 1, 1, 1)
        self.buttonFindPathLogFile = QtGui.QToolButton(self.gridLayoutWidget)
        self.buttonFindPathLogFile.setObjectName("buttonFindPathLogFile")
        self.gridLayout.addWidget(self.buttonFindPathLogFile, 0, 2, 1, 1)
        self.labelLogFile = QtGui.QLabel(self.gridLayoutWidget)
        self.labelLogFile.setObjectName("labelLogFile")
        self.gridLayout.addWidget(self.labelLogFile, 0, 0, 1, 1)
        self.labelParser = QtGui.QLabel(self.gridLayoutWidget)
        self.labelParser.setObjectName("labelParser")
        self.gridLayout.addWidget(self.labelParser, 1, 0, 1, 1)
        self.pathParser = QtGui.QLineEdit(self.gridLayoutWidget)
        self.pathParser.setObjectName("pathParser")
        self.gridLayout.addWidget(self.pathParser, 1, 1, 1, 1)
        self.buttonFindPathParser = QtGui.QToolButton(self.gridLayoutWidget)
        self.buttonFindPathParser.setObjectName("buttonFindPathParser")
        self.gridLayout.addWidget(self.buttonFindPathParser, 1, 2, 1, 1)
        self.labelPgdl = QtGui.QLabel(self.gridLayoutWidget)
        self.labelPgdl.setObjectName("labelPgdl")
        self.gridLayout.addWidget(self.labelPgdl, 6, 0, 1, 1)
        self.pathPgdl = QtGui.QLineEdit(self.gridLayoutWidget)
        self.pathPgdl.setObjectName("pathPgdl")
        self.gridLayout.addWidget(self.pathPgdl, 6, 1, 1, 1)
        self.buttonFindDestinationPgdl = QtGui.QToolButton(self.gridLayoutWidget)
        self.buttonFindDestinationPgdl.setObjectName("buttonFindDestinationPgdl")
        self.gridLayout.addWidget(self.buttonFindDestinationPgdl, 6, 2, 1, 1)
        self.labelTypeParser = QtGui.QLabel(self.gridLayoutWidget)
        self.labelTypeParser.setObjectName("labelTypeParser")
        self.gridLayout.addWidget(self.labelTypeParser, 2, 0, 1, 1)
        self.comboTypeParser = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboTypeParser.setObjectName("comboTypeParser")
        self.comboTypeParser.addItem(QtCore.QString())
        self.comboTypeParser.addItem(QtCore.QString())
        self.comboTypeParser.addItem(QtCore.QString())
        self.comboTypeParser.addItem(QtCore.QString())
        self.comboTypeParser.addItem(QtCore.QString())
        self.comboTypeParser.addItem(QtCore.QString())
        self.gridLayout.addWidget(self.comboTypeParser, 2, 1, 1, 1)
        self.buttonBuild = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBuild.sizePolicy().hasHeightForWidth())
        self.buttonBuild.setSizePolicy(sizePolicy)
        self.buttonBuild.setObjectName("buttonBuild")
        self.gridLayout.addWidget(self.buttonBuild, 7, 2, 1, 1)

        self.retranslateUi(Dialog_Build)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Build)

    def retranslateUi(self, Dialog_Build):
        Dialog_Build.setWindowTitle(QtGui.QApplication.translate("Dialog_Build", "Build Graphic", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonFindPathLogFile.setText(QtGui.QApplication.translate("Dialog_Build", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLogFile.setText(QtGui.QApplication.translate("Dialog_Build", "Log File:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelParser.setText(QtGui.QApplication.translate("Dialog_Build", "Parser:", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonFindPathParser.setText(QtGui.QApplication.translate("Dialog_Build", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPgdl.setText(QtGui.QApplication.translate("Dialog_Build", "Destination Pgdl file: ", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonFindDestinationPgdl.setText(QtGui.QApplication.translate("Dialog_Build", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTypeParser.setText(QtGui.QApplication.translate("Dialog_Build", "TypeParser:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboTypeParser.setItemText(0, QtGui.QApplication.translate("Dialog_Build", "Python Script", None, QtGui.QApplication.UnicodeUTF8))
        self.comboTypeParser.setItemText(1, QtGui.QApplication.translate("Dialog_Build", "Perl Script", None, QtGui.QApplication.UnicodeUTF8))
        self.comboTypeParser.setItemText(2, QtGui.QApplication.translate("Dialog_Build", "Bash Script", None, QtGui.QApplication.UnicodeUTF8))
        self.comboTypeParser.setItemText(3, QtGui.QApplication.translate("Dialog_Build", "C program", None, QtGui.QApplication.UnicodeUTF8))
        self.comboTypeParser.setItemText(4, QtGui.QApplication.translate("Dialog_Build", "C++ program", None, QtGui.QApplication.UnicodeUTF8))
        self.comboTypeParser.setItemText(5, QtGui.QApplication.translate("Dialog_Build", "Java program", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonBuild.setText(QtGui.QApplication.translate("Dialog_Build", "Build", None, QtGui.QApplication.UnicodeUTF8))

